spring:
  application:
    name: meetime-case-tecnico

  profiles:
    active: ${ENVIRONMENT}

auth:
  hubspot:
    url: ${HUB_API}
    api-key: ${USER_API_KEY}
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}

openapi:
  server:
    local: ${LOCAL_URL}
    prd: ${PROD_URL}