spring:
  application.name: meetime-case-tecnico
  jackson.serialization.indent_output: true

  profiles:
    active: ${ENVIRONMENT}

  management:
    endpoints.web.exposure.include:
      - '*'
    endpoint.health.show-details: always
    health.circuitbreakers.enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenHalfToOpenEnabled: true
      waitDurationInOpenState: 5s
      failureRateThreshold: 50 # aqui define a taxa de erro permitida na integração ou seja se metade das requisições falharem
      eventConsumerBufferSize: 10

auth:
  hubspot:
    url: ${HUB_API}
    api-key: ${USER_API_KEY}
    client_id: ${CLIENT_ID}
    client_secret: ${CLIENT_SECRET}

openapi:
  server:
    local: ${LOCAL_URL}
    prd: ${PROD_URL}